<a href="https://colab.research.google.com/github/tejeshvarsk/tensors/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([[1,2], [3,4]])
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
np_array.shape

(2, 2)

In [ ]:
np_array.dtype

dtype('int64')

In [ ]:
data = [[1,2],[3,4]]

In [ ]:
data

[[1, 2], [3, 4]]

In [ ]:
type(data)

list

In [ ]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_np=torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.3378, 0.0612],
        [0.1837, 0.0666]])

In [ ]:
shape = (3,2,)
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.7635, 0.9036],
        [0.4063, 0.0645],
        [0.0947, 0.5747]])

In [ ]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
tensor = torch.rand(3,4)
tensor

tensor([[0.5581, 0.2644, 0.7615, 0.4376],
        [0.3020, 0.8504, 0.7891, 0.5364],
        [0.1441, 0.9068, 0.2402, 0.6005]])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor.shape

torch.Size([3, 4])

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
if (torch.cuda.is_available()):
  tensor = tensor.to("cuda")

In [ ]:
tensor.device

device(type='cuda', index=0)

In [ ]:
tensor= torch.rand(4,4)
tensor

tensor([[0.9992, 0.8777, 0.1952, 0.1207],
        [0.5218, 0.0974, 0.1198, 0.7613],
        [0.3111, 0.8495, 0.8919, 0.9193],
        [0.0618, 0.2755, 0.0824, 0.8384]])

In [ ]:
tensor[0]

tensor([0.9992, 0.8777, 0.1952, 0.1207])

In [ ]:
tensor[:,0]

tensor([0.9992, 0.5218, 0.3111, 0.0618])

In [ ]:
tensor[...,-1]

tensor([0.1207, 0.7613, 0.9193, 0.8384])

In [ ]:
tensor[:,1]=0
tensor

tensor([[0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384]])

In [ ]:
t1=torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[0.9992, 0.0000, 0.1952, 0.1207, 0.9992, 0.0000, 0.1952, 0.1207, 0.9992,
         0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613, 0.5218, 0.0000, 0.1198, 0.7613, 0.5218,
         0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193, 0.3111, 0.0000, 0.8919, 0.9193, 0.3111,
         0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384, 0.0618, 0.0000, 0.0824, 0.8384, 0.0618,
         0.0000, 0.0824, 0.8384]])

In [ ]:
t1.shape

torch.Size([4, 12])

In [ ]:
t2=torch.cat([tensor,tensor,tensor])
t2

tensor([[0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384],
        [0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384],
        [0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384]])

In [ ]:
t2.shape

torch.Size([12, 4])

In [ ]:
tensor

tensor([[0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384]])

In [ ]:
tensor.T

tensor([[0.9992, 0.5218, 0.3111, 0.0618],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.1952, 0.1198, 0.8919, 0.0824],
        [0.1207, 0.7613, 0.9193, 0.8384]])

In [ ]:
y1=tensor @ tensor.T
y1

tensor([[1.0510, 0.6366, 0.5959, 0.1791],
        [0.6366, 0.8661, 0.9689, 0.6803],
        [0.5959, 0.9689, 1.7374, 0.8634],
        [0.1791, 0.6803, 0.8634, 0.7135]])

In [ ]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[1.0510, 0.6366, 0.5959, 0.1791],
        [0.6366, 0.8661, 0.9689, 0.6803],
        [0.5959, 0.9689, 1.7374, 0.8634],
        [0.1791, 0.6803, 0.8634, 0.7135]])

In [ ]:
y3=torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[1.0510, 0.6366, 0.5959, 0.1791],
        [0.6366, 0.8661, 0.9689, 0.6803],
        [0.5959, 0.9689, 1.7374, 0.8634],
        [0.1791, 0.6803, 0.8634, 0.7135]])

In [ ]:
agg = tensor.sum()
agg

tensor(5.8228)

In [ ]:
agg_item=agg.item()
agg_item

5.822810173034668

In [ ]:
type(agg), type(agg_item)

(torch.Tensor, float)

In [ ]:
tensor

tensor([[0.9992, 0.0000, 0.1952, 0.1207],
        [0.5218, 0.0000, 0.1198, 0.7613],
        [0.3111, 0.0000, 0.8919, 0.9193],
        [0.0618, 0.0000, 0.0824, 0.8384]])

In [ ]:
tensor.add_(5)

tensor([[5.9992, 5.0000, 5.1952, 5.1207],
        [5.5218, 5.0000, 5.1198, 5.7613],
        [5.3111, 5.0000, 5.8919, 5.9193],
        [5.0618, 5.0000, 5.0824, 5.8384]])

In [ ]:
tensor

tensor([[5.9992, 5.0000, 5.1952, 5.1207],
        [5.5218, 5.0000, 5.1198, 5.7613],
        [5.3111, 5.0000, 5.8919, 5.9193],
        [5.0618, 5.0000, 5.0824, 5.8384]])

In [ ]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [ ]:
n=t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
t.add_(1)
t

tensor([2., 2., 2., 2., 2.])

In [ ]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [ ]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [ ]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
np.add(n,1, out=n)
n

array([2., 2., 2., 2., 2.])

In [ ]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)